# -*- coding: utf-8 -*-
"""Question 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wgmD0aUNFGn0P9KmeCXFGsE8XTR32i3e
"""

class FindTarget():
  def __init__(self, lst, target):
    self.lst = lst
    self.target = target
    self.cnt = 0
    self.IndexDict = {}

  def SearchSum(self):
    cnt = self.cnt
    lst = self.lst
    target = self.target
    d = self.IndexDict
    l = len(lst)
    for i in range (l):
      for j in range (i+1, l):
        if(lst[i] + lst[j] == target):
          m = []
          cnt += 1
          m.append(i)
          m.append(j)
          d[i] = m
    return d

lst = [int(n) for n in input("Enter search array : ").split(' ')]
target = int(input("Enter target number : "))

TargetFinder = FindTarget(lst, target)
SolutionSet = TargetFinder.SearchSum()
print(SolutionSet)