# -*- coding: utf-8 -*-
"""q1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Gr9j1_sMgifJW5Fkk41lfEm4Cm93i8xz
"""

import math
import torch
x=torch.randint(0,2,(100,))
y=torch.rand(100)
z=0
for i in range(100):
  z=z+((x[i])*math.log2(y[i])+(1-x[i])*math.log2(1-y[i]))
(-z/100).item()