# -*- coding: utf-8 -*-
"""q2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_T9eZUS4oY8n71Lk5C6qTfXLcA1JHEqJ
"""

l=[10,20,10,40,50,60,70]
t=50
class dict():
  d={}
  n=0
  for i in range(len(l)):
    for j in range(len(l)):
      if(l[i]+l[j]==50):
        n=n+1
        d[n]=[i,j]
  print(d)
dict()